import tkinter as tk
import random
import os
from basicClasses import *

GRAVITY = -2
FRICTION = 0.8

MAXHP = 10
HURT_COOLDOWN = 10
HURT_TIME = 0

DASH_COOLDOWN = 15
DASH_SPEED = 28
DASH_TIME = 14

JUMP_STRENGTH = 25
PLR_SPEED = 3
STEP_TIME = 8

ATTACK_COOLDOWN = 15
ATTACK_TIME = 10

WINDOW_DIMENSIONS = Vector2(1280, 720)
WINDOW_BORDERS = 80

A_NONE = 0
A_RANGED = 1
A_RANGED_ACTIVE = 2
A_MELEE = 3
A_MELEE_WINDUP = 4
A_MELEE_ACTIVE = 5

STATE_POOL = [A_MELEE, A_MELEE, A_MELEE, A_RANGED]

PIDER_PROJECTILE_CAP = 3
PIDER_ATTACK_WINDUP = 25
PIDER_ATTACK = 15
